name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  Snyk:
    name: SCA and SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Snyk SCA
        continue-on-error: true
        run: |
          cd frontend
          snyk test --sarif-file-output=snyk-sarif-SCA.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload SARIF file SCA
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: frontend/snyk-sarif-SCA.json
      - name: Snyk SAST
        continue-on-error: true
        run: |
          cd frontend
          snyk code test --sarif-file-output=snyk-sarif-SAST.json
        env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload SARIF file SAST
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: frontend/snyk-sarif-SAST.json
 
  build-images:
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build image
        run: |
          docker build . --file frontend/Dockerfile --tag ${{ github.sha }}
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: scan images
        continue-on-error: true
        run: |
          snyk container test ${{ github.sha }} --file=frontend/Dockerfile --sarif-file-output=snyk-sarif-container.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload SARIF file Container
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: frontend/snyk-sarif-container.json
