name: Code Scan
on:

  pull_request:
    branches: [ "main" ]

jobs:
  Sonarcloud:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Remplazando sonar-project.properties
      uses: datamonsters/replace-action@v2
      with:
        files: 'sonar-project.properties'
        replacements: 'SONAR_PROJECTKEY=${{ secrets.SONAR_PROJECTKEY }},SONAR_ORGANIZATION=${{ secrets.SONAR_ORGANIZATION }}'
            
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  Snyk-SCA-SAST:
    name: SCA and SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: Snyk SCA
        continue-on-error: true
        run: |
          cd frontend
          snyk test --sarif-file-output=snyk-sarif-SCA.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload SARIF file SCA
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: frontend/snyk-sarif-SCA.json
          
      - name: Snyk SAST
        continue-on-error: true
        run: |
          cd frontend
          snyk code test --sarif-file-output=snyk-sarif-SAST.json
        env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload SARIF file SAST
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: frontend/snyk-sarif-SAST.json
 
  Snyk-Container:
    name: Build image to scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build image
        run: |
          docker build . --file Dockerfile --tag ${{ github.sha }}
          
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ github.sha }}
          args: --file=Dockerfile
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
